name: CI

on:
    push:
        branches:
            - main
    pull_request_target:
        branches:
            - main

jobs:
    setup-gcloud:
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: 'Authenticate with Google Cloud'
              id: 'auth'
              uses: google-github-actions/auth@v0.4.0
              with:
                workload_identity_provider: projects/762133163917/locations/global/workloadIdentityPools/github/providers/my-repo
                service_account: github-actions-deployment@egyptian-ratscrew.iam.gserviceaccount.com
            - name: 'Verify authentication'
              run: |
                  gcloud auth list
                  gcloud config list