name: Game Executable

on:
  workflow_dispatch:
  
jobs:
  build-mac:
    permissions:
        id-token: write
        contents: write
    runs-on: macos-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Authenticate with Google Cloud'
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: 'Build the game executable'
        run: |
          echo "Building game executable for macOS"
          ./gradlew desktop:jpackage
        working-directory: ./game-client
      - name: 'Get the filename of the game executable'
        run: |
          echo "Game executable filename: $(ls ./game-client/desktop/build/distribution/*.dmg)"
          echo "FILENAME=$(ls ./game-client/desktop/build/distribution/*.dmg)" >> $GITHUB_ENV
      - name: 'Upload game executable to storage bucket'
        uses: google-github-actions/upload-cloud-storage@v0.3.0
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          path: ${{ env.FILENAME }}
          destination: game-assets-bucket-egyptian-ratscrew/game-dl/mac
  build-windows:
    permissions:
        id-token: write
        contents: write
    runs-on: windows-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Authenticate with Google Cloud'
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: 'Build the game executable'
        run: |
          echo "Building game executable for Windows"
          ./gradlew desktop:jpackage
        working-directory: ./game-client
        
      - name: 'Get the filename of the game executable'
        run: |
          $exePath = Get-ChildItem ./game-client/desktop/build/distribution/*.exe | Select-Object -ExpandProperty FullName
          echo "Full executable path: $exePath"
          
          $exeName = [System.IO.Path]::GetFileName($exePath)
          echo "Game executable filename: $exeName"
          echo "FILENAME=$exeName" | Out-File -FilePath $env:GITHUB_ENV -Append
      
      - name: 'Upload game executable to storage bucket'
        uses: google-github-actions/upload-cloud-storage@v0.3.0
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          path: ${{ env.FILENAME }}
          destination: game-assets-bucket-egyptian-ratscrew/game-dl/win/${{ env.FILENAME }}
      
      - name: 'Upload game executable to storage bucket'
        uses: google-github-actions/upload-cloud-storage@v0.3.0
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          path: ${{ env.FILENAME }}
          destination: game-assets-bucket-egyptian-ratscrew/game-dl/win
  build-linux:
    permissions:
        id-token: write
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Authenticate with Google Cloud'
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - name: 'Build the game executable'
        run: |
          echo "Building game executable for Linux"
          ./gradlew desktop:jpackage
        working-directory: ./game-client
      - name: 'Get the filename of the game executable'
        run: |
          echo "Game executable filename: $(ls ./game-client/desktop/build/distribution/*.deb)"
          echo "FILENAME=$(ls ./game-client/desktop/build/distribution/*.deb)" >> $GITHUB_ENV
      - name: 'Upload game executable to storage bucket'
        uses: google-github-actions/upload-cloud-storage@v0.3.0
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          path: ${{ env.FILENAME }}
          destination: game-assets-bucket-egyptian-ratscrew/game-dl/linux
