name: Game Executable

on:
  workflow_dispatch:
  
jobs:
  build-mac:
    permissions:
        id-token: write
        contents: write
    runs-on: macos-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Authenticate with Google Cloud'
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: 'Build the game executable'
        run: |
          echo "Building game executable for macOS"
          ./gradlew desktop:jpackage
        working-directory: ./game-client
      - name: 'Get the filename of the game executable'
        run: |
          echo "Game executable filename: $(ls ./game-client/desktop/build/distribution/*.dmg)"
          echo "FILENAME=$(ls ./game-client/desktop/build/distribution/*.dmg)" >> $GITHUB_ENV
      - name: 'Upload game executable to storage bucket'
        uses: google-github-actions/upload-cloud-storage@v0.3.0
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          path: ${{ env.FILENAME }}
          destination: game-assets-bucket-egyptian-ratscrew/game-dl/mac
  build-windows:
    permissions:
        id-token: write
        contents: write
    runs-on: windows-latest
    outputs:
      filename: ${{ steps.set_filename.outputs.filename }}
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Authenticate with Google Cloud'
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: 'Build the game executable'
        run: |
          echo "Building game executable for Windows"
          ./gradlew desktop:jpackage
        working-directory: ./game-client

      - name: 'Get the filename of the game executable'
        run: |
          $exePath = Get-ChildItem ./game-client/desktop/build/distribution/*.exe | Select-Object -ExpandProperty FullName
          echo "Game executable filename: $exePath"
          echo "FILENAME=$exePath" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "::set-output name=filename::$exePath"
    
      - name: 'Upload game executable to storage bucket'
        uses: google-github-actions/upload-cloud-storage@v0.3.0
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          path: ${{ env.FILENAME }}
          destination: game-assets-bucket-egyptian-ratscrew/game-dl/win
  rename-win-build:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: 'Install Google Cloud SDK'
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: 'Rename uploaded file'
        run: |
          # Extract just the filename from the full path
          FILENAME="${{ needs.build-windows.outputs.filename }}"
          BASENAME=$(basename "$FILENAME")

          # Define source and destination URIs
          SOURCE="gs://game-assets-bucket-egyptian-ratscrew/game-dl/win/$FILENAME"
          DESTINATION="gs://game-assets-bucket-egyptian-ratscrew/game-dl/win/$BASENAME"

          echo "Copying from $SOURCE to $DESTINATION"
          gsutil cp "$SOURCE" "$DESTINATION"
          gsutil rm "$SOURCE"

  build-linux:
    permissions:
        id-token: write
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Authenticate with Google Cloud'
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - name: 'Build the game executable'
        run: |
          echo "Building game executable for Linux"
          ./gradlew desktop:jpackage
        working-directory: ./game-client
      - name: 'Get the filename of the game executable'
        run: |
          echo "Game executable filename: $(ls ./game-client/desktop/build/distribution/*.deb)"
          echo "FILENAME=$(ls ./game-client/desktop/build/distribution/*.deb)" >> $GITHUB_ENV
      - name: 'Upload game executable to storage bucket'
        uses: google-github-actions/upload-cloud-storage@v0.3.0
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          path: ${{ env.FILENAME }}
          destination: game-assets-bucket-egyptian-ratscrew/game-dl/linux
