name: Infrastructure

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Authenticate with Google Cloud'
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - name: 'Retrieve DB password'
        run: |
          echo "DB_PASSWORD=$(gcloud secrets versions access latest --secret=db_password)" >> $GITHUB_ENV
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
      - name: 'Run Terraform'
        env:
          TF_VAR_db_password: ${{ env.DB_PASSWORD }}
        run: |
          cd infrastructure/gcp
          terraform init
          terraform import google_compute_firewall.http projects/egyptian-ratscrew/global/firewalls/http
          terraform import google_compute_firewall.ssh projects/egyptian-ratscrew/global/firewalls/ssh
          terraform import google_compute_firewall.icmp projects/egyptian-ratscrew/global/firewalls/icmp
          terraform import google_storage_bucket.game_assets_bucket game-assets-bucket-egyptian-ratscrew
          terraform import google_sql_database_instance.game_db projects/egyptian-ratscrew/instances/game-db
          terraform import google_compute_instance.game_server projects/egyptian-ratscrew/zones/us-west1-a/instances/game-server
          terraform import google_sql_user.default egyptian-ratscrew/game-db/admin
          terraform import google_compute_network.vpc_network projects/egyptian-ratscrew/global/networks/vpc-network
          terraform import google_compute_global_address.private_ip_range projects/egyptian-ratscrew/global/addresses/private-ip-range
          terraform plan
          terraform apply -auto-approve
          
# terraform import google_service_networking_connection.private_vpc_connection projects/egyptian-ratscrew/regions/us-west1/serviceNetworkingConnections/servicenetworking.googleapis.com%2Fconnections%2Fvpc-network