name: New Relic Infra Agent Setup

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  nr-infra-agent-setup:
    permissions:
        id-token: write
        contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Authenticate with Google Cloud'
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - name: 'Retrieve New Relic api key'
        run: |
          echo "NR_API_KEY=$(gcloud secrets versions access latest --secret=nr_api_key)" >> $GITHUB_ENV
      - name: 'Get game-server IP'
        run: |
          echo "GAME_SERVER_IP=$(gcloud compute instances describe game-server --zone=us-west1-a --format='value(networkInterfaces[0].accessConfigs[0].natIP)')" >> $GITHUB_ENV
      - name: 'Install New Relic infrastructure agent'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.GAME_SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY=${{env.NR_API_KEY}} NEW_RELIC_ACCOUNT_ID=4406929 /usr/local/bin/newrelic install -y
      - name: 'Copy log config to game-server'
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.GAME_SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'game-server/etc/game-server-log-config.yml'
          target: '/etc/newrelic-infra/integrations.d/'
      - name: 'Restart New Relic infrastructure agent'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.GAME_SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart newrelic-infra
